# Generated by MikroTik DHCP Config Generator
# School: {{SCHOOL_NAME}}
# Date: {{DATE}}

/interface bridge
add auto-mac=yes comment=defconf name=bridge

/interface wireless
set [ find default-name=wlan1 ] band=2ghz-b/g/n channel-width=20/40mhz-XX \
    distance=indoors frequency=auto installation=indoor mode=ap-bridge ssid=\
    {{SSID}} wireless-protocol=802.11

/interface bridge port
add bridge=bridge comment=defconf interface=ether1
add bridge=bridge comment=defconf interface=ether2
add bridge=bridge comment=defconf interface=ether3
add bridge=bridge comment=defconf interface=ether4
add bridge=bridge comment=defconf interface=pwr-line1
add bridge=bridge comment=defconf interface=wlan1

/ip pool
add name=dhcp_pool0 ranges={{DHCP_POOL_RANGES}}

/ip dhcp-server
add address-pool=dhcp_pool0 disabled=no interface=bridge name=dhcp1

/ip address
add address={{ROUTER_IP}}/{{SUBNET_CIDR}} interface=bridge network={{NETWORK_ADDRESS}}

/ip dhcp-server network
add address={{NETWORK_ADDRESS}}/{{SUBNET_CIDR}} dns-server={{DNS_SERVERS}} gateway={{GATEWAY}}

{{STATIC_LEASES}}
/ip dns
set servers={{DNS_SERVERS}}

/ip dns static
add address=192.168.88.1 comment=defconf name=router.lan
